name: hero_animation
description: Hero-animates it's child from one layout position to another within the same Route.
version: 1.1.3
homepage: https://github.com/kirn-tech/hero_animation.git

environment:
  sdk: '>=2.17.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

